name: climora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.4
  intl: ^0.19.0
  flutter_animate: ^4.5.2
  geolocator: ^13.0.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- [ADDED] 1. Dito natin nilagay yung package ---
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600

# --- [ADDED] 2. Settings para sa Icon (Sa pinaka-baba ito ilalagay) ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" # Siguraduhin na may image file ka dito!
  min_sdk_android: 21
  change_app_package_name: ^1.1.0